name: schedule job

on:
  schedule:
    - cron: "17 10 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hi Prashant git workflow done"
